spring:
  application:
    name: fintech-Bank-App
  datasource:
    url: jdbc:postgresql://localhost:5432/fintechBankDB
    username: postgres
    password: newpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: skytecomputer@gmail.com
    password: nvmo qloa syff xrec
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li66crkpr1Mv0aIC
            client-secret: cd0ac55f07feb4f76f77e9c9e3e00982afef2c83
          google:
            client-id: 228783255239-1r20mt6fdufo8g8bn12nh0c3n4vr4o32.apps.googleusercontent.com
            client-secret: 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
  doc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    api-docs:
      path: /v3/api-docs

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

server:
  port: 8081

app:
  jwt-secret: 8e3f0b1d5d2a4c8b92e1fc1a765bf2434d6c72e6f5b943e2c1c1e2d6b4db7a22
  jwt-expiration: 86400000

twilio:
  accountSid: AC76e5b4b4000bb517c34d4ff3321383df
  authToken: 39b3e4de4d6e8e78c96a7d2a679e3fbb
  phoneNumber: +12566241584

# Paystack Configuration
paystack:
  secret:
    key: sk_test_ec45ec68e676c8d3706f03cd8966352daa084991
  public:
    key: pk_test_5fdf2da3a1fcb9ad9cdd89a93b6c0520bb1332f4
  base:
    url: https://api.paystack.co




